baseurl = "https://annjose.com/"
languageCode = "en-us"
title = "Reflections"
theme = "blackburn"
author = "Ann Catherine Jose"
copyright = "&copy; 2025. All rights reserved."
canonifyurls = true
pagination.pagerSize = 10
disablePathToLower = true

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Ann Catherine Jose"
  brand = "Reflections"
  # Old googleAnalytics = "UA-75357261-1"
  googleAnalytics = "G-2PEL4BVYJE"
  disqus = "anncjose"
  dateFormat = "02 Jan 2006"
  siteId = "annjose-blog"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    style = "dracula"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fas fa-home fa-fw'></i>"
    weight = 10
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "My Blog"
    pre = "<i class='fas fa-pen-to-square fa-fw'></i>"
    weight = 20
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "AI & LLMs"
    pre = "<i class='fas fa-hexagon-nodes fa-fw'></i>"
    weight = 30
    identifier = "llm"
    url = "/tags/LLM"
  [[menu.main]]
    name = "Tech Explorations"
    pre = "<i class='fas fa-magnifying-glass fa-fw'></i>"
    weight = 40
    identifier = "tech-explorations/"
    url = "/tags/tech-explorations"
  [[menu.main]]
    name = "Personal Growth"
    pre = "<i class='fas fa-arrow-up-right-dots fa-fw'></i>"
    weight = 50
    identifier = "personal-growth"
    url = "/tags/personal-growth"
  [[menu.main]]
    name = "Web Development"
    pre = "<i class='fas fa-globe fa-fw'></i>"
    weight = 60
    identifier = "web-development/"
    url = "/tags/web-development"
  [[menu.main]]
    name = "Mobile Tech"
    pre = "<i class='fas fa-mobile-screen fa-fw'></i>"
    weight = 70
    identifier = "mobile-tech"
    url = "/tags/mobile-tech"
  [[menu.main]]
    name = "About Me"
    pre = "<i class='fas fa-user fa-fw'></i>"
    weight = 100
    identifier = "about"
    url = "/about/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  bluesky = "annjose.com"
  # twitter = ""
  # facebook = "*"
  # googleplus = "*"
  # weibo = "*"

  # SNS photo/video sharing
  # instagram = "*"
  # flickr = "*"
  # pinterest = "*"
  # youtube = "*"
  # vimeo = "*"
  # vine = "*"
  # slideshare = "*"

  # SNS career oriented
  linkedin = "annjose"
  # xing = "*"

  # SNS news
  # reddit = "*"
  hackernews = "annjose"

  # Techie
  github = "annjose"
  # bitbucket = "*"
  # stackoverflow = "402100"